package by.issue_tracker.command;

public enum CommandName {
    SIGN_IN,
    GET_USERS,
    UPDATE_USER,
    DELETE_USER,
    CREATE_USER,
    GET_PROJECTS,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    CREATE_PROJECT,
    GET_SPRINTS,
    UPDATE_SPRINT,
    DELETE_SPRINT,
    CREATE_SPRINT,
    GET_TASKS,
    UPDATE_TASK,
    DELETE_TASK,
    CREATE_TASK,
    GET_COMMENTS,
    UPDATE_COMMENT,
    DELETE_COMMENT,
    CREATE_COMMENT
}
